##
## Test Suites
##

    modified.files.includes[relevant][headless-builder-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    relevant.rule.names=headless-builder-java-rule

    test.batch.names[relevant][headless-builder-java-rule]=\
        modules-integration-db-partition-postgresql163,\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[headless-builder-java-rule][relevant][modules-integration-db-partition-postgresql163]=\
        apps/headless/headless-builder/**/APIPropertyObjectDefinitionDeployerTest.java

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][headless-builder-java-rule]=\
        **/headless-builder/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][headless-builder-java-rule]=\
        **/headless-builder/**/*Test.java

##
## Testray
##

    testray.main.component.name=API Builder